#!/bin/sh

# Gradle wrapper start-up script for POSIX systems.
# Generated by Gradle. Do not edit manually.

set -e

APP_HOME=$(cd "$(dirname "$0")" && pwd)
GRADLE_WRAPPER_JAR="$APP_HOME/gradle/wrapper/gradle-wrapper.jar"

if [ ! -f "$GRADLE_WRAPPER_JAR" ]; then
    echo "Error: $GRADLE_WRAPPER_JAR not found."
    echo "Run 'gradle wrapper' to generate the Gradle wrapper files."
    exit 1
fi

# Determine JAVA_HOME
if [ -n "$JAVA_HOME" ]; then
    JAVACMD="$JAVA_HOME/bin/java"
else
    JAVACMD="java"
fi

exec "$JAVACMD" \
    -classpath "$GRADLE_WRAPPER_JAR" \
    org.gradle.wrapper.GradleWrapperMain "$@"
